zpool_SOURCES = \
	zpool_iter.c \
	zpool_main.c \
	zpool_util.c \
	zpool_util.h \
	freebsd_zpool_vdev.c

objs = \
	zpool_iter.o \
	zpool_main.o \
	zpool_util.o \
	freebsd_zpool_vdev.o

PROG=zpool

CFLAGS+= -Wno-absolute-value
LDFLAGS+= -L. -lzpool -luutil -ltpool -lnvpair -lzfs -L/usr/local/lib -lintl -lspl -lgeom -lzfs_core -lavl
include $(ZFSBASE)/cmd/Makefile.bsd.inc


