
$(MODULE)-objs += nvpair.o
$(MODULE)-objs += fnvpair.o
$(MODULE)-objs += nvpair_alloc_spl.o
$(MODULE)-objs += nvpair_alloc_fixed.o

objs = $($(MODULE)-objs)
objs+= $($(MODULE)-x86)
all: nvpair.ko

include $(ZFSBASE)/Makefile.bsd.inc

nvpair.ko:  $(objs)
	ld -r -d -o $@ $(objs)
