
$(MODULE)-objs += uconv.o
$(MODULE)-objs += u8_textprep.o

objs = $($(MODULE)-objs)
objs+= $($(MODULE)-x86)
all: unicode.ko

include $(ZFSBASE)/module/Makefile.bsd.inc

unicode.ko: $(objs)
	ld -r -d -o unicode.ko $(objs)

