ZFSBASE := $(shell pwd)/..

all: zfs.ko

archives := avl/avl.ko lua/lua.ko nvpair/nvpair.ko zcommon/zcommon.ko zfs/zfs_common.ko \
	unicode/unicode.ko os/freebsd/zfs/zfs_os.ko os/freebsd/spl/spl.ko

zfs.ko: ${archives}
	ld -m elf_x86_64_fbsd -d -warn-common --build-id=sha1 -r -d -o zfs.ko ${archives}

avl/avl.ko:
	$(MAKE) -f Makefile.bsd -C avl
lua/lua.ko:
	$(MAKE) -f Makefile.bsd -C lua
nvpair/nvpair.ko:
	$(MAKE) -f Makefile.bsd -C nvpair
unicode/unicode.ko:
	$(MAKE) -f Makefile.bsd -C unicode
zcommon/zcommon.ko:
	$(MAKE) -f Makefile.bsd -C zcommon
zfs/zfs_common.ko:
	$(MAKE) -f Makefile.bsd -C zfs



os/freebsd/spl/spl.ko:
	$(MAKE) -f Makefile.bsd -C os/freebsd/spl

os/freebsd/zfs/zfs_os.ko:
	$(MAKE) -f Makefile.bsd -C os/freebsd/zfs

